sonar.projectKey=anneBaque_fprime
sonar.organization=anneBaque
sonar.projectName=F Prime Core Analysis

# --- EL FILTRO CRÍTICO ---
# Le decimos que la raíz del código es SOLO Fw
sonar.sources=.
sonar.inclusions=Fw/**/*

# Exclusiones para limpiar ruido dentro de Fw
sonar.exclusions=\
  **/test/**,\
  **/tests/**,\
  **/*Test.cpp,\
  **/*Test.hpp,\
  **/Ac/**,\
  **/docs/**

# Configuración para C++ (Fprime)
sonar.cfamily.compile-commands=compile_commands.json
sonar.sourceEncoding=UTF-8