sonar.projectKey=anneBaque_fprime
sonar.organization=anneBaque
sonar.projectName=F Prime Core Analysis

# Analizar solo la carpeta Fw
sonar.sources=Fw,Os,Svc
sonar.inclusions=Fw/**
sonar.exclusions=Fw/**/test/**, Fw/**/tests/**, Fw/**/*Test.cpp, Fw/**/*Test.hpp, Fw/**/Ac/**

# Configuración de C++
sonar.cfamily.compile-commands=compile_commands.json
sonar.sourceEncoding=UTF-8
sonar.cfamily.threads=4

sonar.sources=Fw,Os,Svc
sonar.cfamily.gcov.reportsPath=coverage.xml
sonar.junit.reportPaths=test_results.xml
sonar.lang.opt.cpp.compiler=gcc