# Información del proyecto
sonar.projectKey=anneBaque_fprime
sonar.organization=anneBaque

# Nombre y versión del proyecto
sonar.projectName=F Prime Core Analysis
sonar.projectVersion=1.0

# Solo analizar estas carpetas específicas
sonar.sources=Fw/

# Tipos de archivo a incluir (C/C++)
sonar.inclusions=Fw/Buffer/**, Fw/Cmd/**, Fw/Com/**, Fw/Comp/**, Fw/DataStructures/**, Fw/Dp/**, Fw/FilePacket/**, Fw/Interfaces/**, Fw/Log/**, Fw/Logger/**, Fw/Obj/**, Fw/Port/**, Fw/Ports/**, Fw/Prm/**, Fw/SerializableFile/**, Fw/Sm/**, Fw/Time/**, Fw/Tlm/**, Fw/Trap/**, Fw/Types/**

# Exclusiones dentro de esas carpetas (si hay algo que no quieres)
sonar.exclusions=\
  **/build/**,\
  **/build-*/**,\
  **/test/**,\
  **/tests/**,\
  **/*Test.cpp,\
  **/*Test.hpp, Fw/Test/**, **/docs/**

# Encoding
sonar.sourceEncoding=UTF-8

# Excluir archivos generados automáticamente
sonar.cpd.exclusions=**/Ac/**,**/*Ac.cpp,**/*Ac.hpp

# Excluir de cobertura
sonar.coverage.exclusions=**/test/**,**/*Test.cpp

sonar.python.version=3.8,3.9,3.10,3.11

# Configuración para C/C++ - usar compilation database
sonar.cfamily.compile-commands=build/compile_commands.json

# Excluir archivos generados automáticamente
sonar.cpd.exclusions=**/Ac/**,**/*Ac.cpp,**/*Ac.hpp

# Excluir de cobertura
sonar.coverage.exclusions=**/test/**,**/*Test.cpp


sonar.language=cpp